name: CI de Spring Boot

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v3
      
      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Dar permisos de ejecución a mvnw
        run: chmod +x mvnw
          
      - name: Compilar y ejecutar pruebas con Maven
        run: ./mvnw clean verify
    
