name: CI de Spring Boot

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: luis1234
          MYSQL_DATABASE: db_user_springboot
          MYSQL_USER: testuser # Nuevo usuario
          MYSQL_PASSWORD: luis1234 # Nueva contraseña
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v3

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Dar permisos de ejecución a mvnw
        run: chmod +x mvnw
      
      - name: Esperar a que MySQL esté listo
        run: |
          sudo apt-get install -y mariadb-client
          mysql --host=127.0.0.1 --port=3306 --user=root --password=mypassword --execute="SELECT 1;"

      - name: Compilar y ejecutar pruebas con Maven
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_user_springboot
          SPRING_DATASOURCE_USERNAME: testuser
          SPRING_DATASOURCE_PASSWORD: luis1234
        run: ./mvnw clean verify